// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixkudnfwfcojfgvngnkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4a3VkbmZ3ZmNvamZndm5nbmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjAzODYsImV4cCI6MjA3MDczNjM4Nn0.29hCyC5ewUub1mbTTi-LF0cOPD3vAIlLaeb83u1w1oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});